### PR TITLE
testing with meta data, intro, methods & first 3 figures

### PR DESCRIPTION
**Pull request by katrinleinweber**

### CODE REVIEW

**Comment by katrinleinweber** [comment]
Argh, sorry! I hadn't used the "send pull request" feature in GitHub for Mac before and didn't realise it would send it here, instead of to the main branch of my fork m-(

**Comment by hubgit** [comment]
No worries :) It'll probably be easier if you make a separate clone of the repository, rather than a fork - I think we'll move to that way of doing things in general, soon.

**Comment by katrinleinweber** [comment]
Yeah, but will integrating updates from this "parent" repo into non-forked "child" repos work easily then?

**Comment by hubgit** [comment]
The plan for the next version - that I'm working on at the moment - is to separate the article template (that which generates the bare HTML) and the article display (that which makes it look nice and interactive) into two separate components. That way an author can start a fresh clone of the article template for each new paper, and make their own edits, and the display of the article can be updated independently.

It should be almost as easy to pull updates into a cloned repository as into a forked repository if needed (they're basically the same thing apart from a bit of metadata), although it will probably need to be done on the command line.

**Pull request closed without merging**
