### PR TITLE
Adding simple example of mathjax in the example article

### PR DESCRIPTION
**Pull request by drvinceknight**
Note that mathjax sometimes needs the usual LaTeX delimiters to be escaped. This is the case here.

You can see a rendered version of this pull request here: http://vincent-knight.com/paper-now/

Also, this would imply that the [wiki](https://github.com/PeerJ/paper-now/wiki/Text-Formatting) needs to be updated but I'll wait to see if you are happy with this PR to do that.

Love the look of this by the way :+1: Hoping to make use of it :speedboat:

### CODE REVIEW

**Comment by drvinceknight** [comment]
(Apologies for the mess with the commits, tried to rebase and then all hell got unleashed - if it's an issue let me know and I'll fix it, although you might not want the PR anyway in which case it's no bother :D)

**Comment by hubgit** [comment]
Thanks for the example - I've added it in [a separate commit](https://github.com/PeerJ/paper-now/commit/7183a6f1764343298a8ce088848b726150dbf0c2), rather than dealing with rebasing.

**Comment by drvinceknight** [comment]
Ouch! Way to take my PR away (don't think you would have had to 'deal with rebasing')... Glad it's in :+1:

**Comment by hubgit** [comment]
Apologies for stealing your thunder :worried:

Would you be able to contribute a more complex "display" equation - the type of thing that would actually appear in a paper?

**Comment by drvinceknight** [comment]
> Apologies for stealing your thunder :worried:

Just eager to be able to say I helped :) Love the look of this and trying to see when I'll next use :+1: 

> Would you be able to contribute a more complex "display" equation - the type of thing that would actually appear in a paper?

I'm on it!

**Pull request closed without merging**
