### PR TITLE
Adding more complicated equation (stemming from queueing theory)

### PR DESCRIPTION
**Pull request by drvinceknight**
As discussed here: #11

### CODE REVIEW

**Comment by drvinceknight** [comment]
(Let me know if there's anything you'd like me to change)

You can see it here: http://vincent-knight.com/paper-now/

Note that there are various things that need escaping (this is how I've had to learn to use mathjax with jekyll). I could add something about that on the wiki if that's helpful.

**Comment by hubgit** [comment]
Nice one, thanks.

Instead of having to escape all of Markdown's special characters within the LaTeX code, how about wrapping the whole equation in a `<div>` (or a `<span>`, for inline equations), so the whole block will be copied directly into the output without being processed as Markdown?

`<div>\[ \sum_{i=0}^{\infty}\pi_i=\sum_{i=0}^{\infty}\rho^i\pi_0=\frac{\pi_0}{1-\rho}=1 \]</div>`

**Comment by drvinceknight** [comment]
Did not know that that worked! Learn something new everyday :D :+1:

**Comment by hubgit** [comment]
According to the documentation, Markdown in block-level elements (e.g.
"div") is not processed, but Markdown in inline elements (e.g. "span") is.

http://daringfireball.net/projects/markdown/syntax#html

**Comment by drvinceknight** [comment]
Sweet :+1: Thanks.

**Pull request merged**
